#
#  Author: KhulnaSoft Ltd
#  Date: 2019-03-01 17:11:37 +0000 (Fri, 01 Mar 2019)
#
#  vim:ts=4:sts=4:sw=4:noet
#
#  https://github.com/KhulnaSoft/DevX/tree/main/docker-images
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/KhulnaSoft
#

REPO := khulnasoft/opentsdb

include ../Makefile.in
