#  vim:ts=2:sts=2:sw=2:et
#
#  Author: KhulnaSoft Ltd
#  Date: 2020-03-18 14:54:45 +0000 (Wed, 18 Mar 2020)
#
#  https://github.com/KhulnaSoft/DevX/tree/main/docker-images
#
#  License: see accompanying KhulnaSoft Ltd LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/KhulnaSoft
#

version: '3'
services:
  appveyor-ubuntu:
    image: khulnasoft/appveyor:${VERSION:-ubuntu}
