#
#  Author: KhulnaSoft Ltd
#  Date: 2022-06-20 15:09:09 +0100 (Mon, 20 Jun 2022)
#
#  vim:ts=4:sts=4:sw=4:noet
#
#  https://github.com/KhulnaSoft/DevX/tree/main/docker-images
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/company/khulnasoft
#

REPO := khulnasoft/tfenv

include ../Makefile.in
