#  [% VIM_TAGS %]
#
#  Author: KhulnaSoft Ltd
#  Date: [% DATE # 2013-09-30 13:41:20 +0100 (Mon, 30 Sep 2013) %]
#
#  [% URL %]
#
#  [% LICENSE %]
#
#  [% MESSAGE %]
#
#  [% LINKEDIN %]
#

name 'khulnasoft-mymodule'
version '0.0.1'
dependency 'khulnasoft/etc', '1.2.3'
description ""
author "KhulnaSoft Ltd"
project_page "https://github.com/khulnasoft"
license "Apache License"
